plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.1.20'
    id 'java-gradle-plugin'
    id "com.gradle.plugin-publish" version '1.2.1'
    id("maven-publish")
}

repositories {
    jcenter()
}

dependencies {
    compileOnly gradleApi()

    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.20"
    implementation "com.squareup:kotlinpoet:2.1.0"

    // JSON Parsing
    implementation "com.google.code.gson:gson:2.8.2"
}

gradlePlugin {
    plugins {
        eventsGenerator {
            id = 'com.appsci.words.eventsdroid'
            implementationClass = 'com.appsci.words.eventsdroid.EventsGeneratorPlugin'
        }
    }
}

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())

group = "com.appsci.words"
version = "1.0.0-alpha11"

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Promova/Eventsdroid")
            credentials {
                username = properties["github.actor"] as String
                password = properties["github.token"] as String
            }
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

compileKotlin {
    kotlinOptions.jvmTarget = "17"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "17"
}
